name: Validate JSONs Alternative

on: [push, pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peternewman/json-linter@peternewman-attempt-fix
    - run: |
       sudo npm install -g jsonlint
       sudo apt-get install fd-find
       fdfind --extension json -X ls -ld -E rdm-schema.json
       fdfind --extension json -E rdm-schema.json --exec jsonlint --quiet --compact --validate rdm-schema.json
