name: Validate JSONs Alternative

on: [push, pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peternewman/json-linter@peternewman-attempt-fix
